### ISSUE TITLE
ephemeral paginator doesn't handle cancellation correctly

### ISSUE THREAD

**Issue by MathieuDR** [d4n3436/Fergun.Interactive#1]
When using an ephemeral paginator (StaticPaginator in my case) the 'cancellation' button does not handle the interaction as expected.

It disables the buttons while it's "processing" the interaction, but re-enables them afterwards. These buttons will however not be handled anymore.

I've tried different Cancellation actions, but noone of them works, until you remove the ephermal flag on the reply.

```csharp
public async Task CountHistory(ApplicationCommandContext context, IGuildUser user) {
            var countInfo = _counterService.GetCountInfo(user.ToGuildUserDto());

            var historyPagesInformation = CountHistoryToString(countInfo);
            var pages = new List<PageBuilder>();
            foreach (var page in historyPagesInformation) {
                var descriptionBuilder = new StringBuilder();
                descriptionBuilder.AppendLine($"Total count for {user.DisplayName()}: {countInfo.CurrentCount}.");
                descriptionBuilder.AppendLine("```diff");
                descriptionBuilder.Append(page);
                descriptionBuilder.AppendLine("```");

                var builder = new PageBuilder()
                    .WithCurrentTimestamp()
                    .WithTitle($"History for {user.DisplayName()}")
                    .WithDescription(descriptionBuilder.ToString());
                
                pages.Add(builder);
            }

            var paginator = new StaticPaginatorBuilder()
                .AddUser(context.GuildUser)
                .WithPages(pages)
                .WithActionOnCancellation(ActionOnStop.DeleteInput);

            SocketInteraction interaction = context.InnerContext;
            //await _interactiveService.(paginator.Build() ,interaction, ephemeral: true);
            _ = _interactiveService.SendPaginatorAsync(paginator.Build() ,interaction, ephemeral: false);
        }

**Comment by d4n3436** [comment]
Hi, currently neither ephemeral paginators nor ephemeral selections supports "actions on stop" (cancellation/timeout/success).

This is because ephemeral messages cannot be modified without using the interaction itself, and the lib currently defers the interaction and then modifies the message, which is not possible for ephemeral messages.

I might add support for "actions on stop" in ephemeral messages by directly modifying the message using the interaction object, but I will have to rework the post-execution handling because the callbacks will now have to return the interaction.

Another problem with ephemeral messages is `AlwaysAcknowledgeInteractions`. The lib supports both states so it can know if an interaction has been already deferred, but if `AlwaysAcknowledgeInteractions` is `true`, then the lib won't be able to apply the "actions on stop" because it can't modify messages without the interaction. I will probably add a warning for this.

I will mark this as a bug since this is (technically) a bug.

**Comment by d4n3436** [comment]
I will make a release that includes the fix soon, but you can already build from source and use it if you want to.
