### ISSUE TITLE
InteractiveService throws for no reason when using DeferredUpdateMessage.

### ISSUE THREAD

**Issue by SquirrelKiev** [d4n3436/Fergun.Interactive#32]
The interactionType that uses a call to `ModifyOriginalResponseAsync` (`DeferredUpdateMessage`) throws an `ArgumentException` for an unknown reason in `InteractiveService.SendOrModifyMessageAsync` for slash commands. Unlike the exception suggests, `ModifyOriginalResponseAsync` can be used in slash commands.

The only alternative is using `GetOriginalResponseAsync` and passing that in, which, depending on the permissions/context the bot is in, Discord complains about and it doesn't work. (Discord is more picky about messages being edited in that way)

**Comment by d4n3436** [comment]
Can you please send a stack trace and sample code?

**Comment by SquirrelKiev** [comment]
```cs
using Discord.Interactions;
using Fergun.Interactive;
using Fergun.Interactive.Pagination;

namespace Asahi.Modules;

public class TestModule(InteractiveService interactive) : BotModule
{
    [SlashCommand("test", "hello!")]
    public async Task TestSlash()
    {
        await DeferAsync();

        var paginator = new StaticPaginatorBuilder()
            .WithPages([new PageBuilder().WithText("hello!")])
            .WithDefaultEmotes();

        await interactive.SendPaginatorAsync(paginator.Build(), Context.Interaction, TimeSpan.FromMinutes(1),
            InteractionResponseType.DeferredUpdateMessage);
    }
}
```

```
System.ArgumentException: Interaction response type DeferredUpdateMessage can only be used on component interactions. (Parameter 'responseType')
   at Fergun.Interactive.InteractiveGuards.ValidResponseType(InteractionResponseType responseType, IDiscordInteraction interaction, String parameterName)
   at Fergun.Interactive.InteractiveService.SendOrModifyMessageAsync[TOption](IInteractiveElement`1 element, IDiscordInteraction interaction, InteractionResponseType responseType, Boolean ephemeral)
   at Fergun.Interactive.InteractiveService.SendPaginatorAsync(Paginator paginator, IDiscordInteraction interaction, Nullable`1 timeout, InteractionResponseType responseType, Boolean ephemeral, Action`1 messageAction, Boolean resetTimeoutOnInput, CancellationToken cancellationToken)
   at Asahi.Modules.TestModule.TestSlash()
   at Discord.Interactions.Builders.ModuleClassBuilder.<>c__DisplayClass11_0.<<CreateCallback>g__ExecuteCallback|1>d.MoveNext()
   --- End of inner exception stack trace ---
```

**Comment by d4n3436** [comment]
The value that is passed into the `responseType` is either the response type the library should use or the one that was already used (for deferred interactions). The exception occurs because the library expects a component interaction when `InteractionResponseType.DeferredUpdateMessage` is passed ([Discord says it's only valid for component interactions](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-interaction-callback-type)).

The response type that should be passed is `InteractionResponseType.DeferredChannelMessageWithSource` (the one `DeferAsync()` uses).

**Comment by SquirrelKiev** [comment]
Apologies, sent this report at 4am my time and sent the wrong codeblock haha

```cs
using Discord.Interactions;
using Fergun.Interactive;
using Fergun.Interactive.Pagination;

namespace Asahi.Modules;

public class TestModule(InteractiveService interactive) : BotModule
{
    [SlashCommand("test", "hello!")]
    public async Task TestSlash()
    {
        await DeferAsync();

        await FollowupAsync("hi!");

        var paginator = new StaticPaginatorBuilder()
            .WithPages([new PageBuilder().WithText("hello!")])
            .WithDefaultEmotes();

        await interactive.SendPaginatorAsync(paginator.Build(), Context.Interaction, TimeSpan.FromMinutes(1),
            InteractionResponseType.DeferredUpdateMessage);
    }
}
```

**Comment by d4n3436** [comment]
I see. You need to get the return value of `FollowupAsync()` and pass it to the overload of `SendPaginatorAsync()` that accepts a message.
For ephemeral interactions, I don't think it's currently supported because modifying an ephemeral message without an interaction was not possible at the time I was writing the library/API, and it's not really common to defer and send a followup before sending a paginator.

**Comment by SquirrelKiev** [comment]
iirc editing an interaction's message using the message edit stuff (passing in the return value of FollowupAsync) instead of ModifyOriginalResponseAsync causes issues in some situations because of the permissions that Discord grants. Think user apps are one of them?

**Comment by d4n3436** [comment]
I've tried to use it in a user app and there seems to be a bug in Discord.Net (I get a NRE on `ModifyAsync()`) so I can't really test it.

Anyways, I've removed the restriction on `InteractionResponseType.DeferredUpdateMessage` and limited it to `InteractionResponseType.UpdateMessage`, which actually requires a component interaction. I'll release a new version soon.
